Excel headers                     Database variable name             

Group                             'grp'                       
Jkt FITMODEL                      'Jkt_FITMODEL'                       
Order #                           'orderno'                  question ❓ 
Marker #                          'Customer_Name'            how to choose 'SLVOUT'(Jkt SLVOUT RIGHT or Jkt SLVOUT LEFT)   
Customer Name                     'Marker'                   for jacket ?           
Cloth Article                     'Cloth_Article'      
Cloth                             'Cloth'                    how to choose 'INSEAM'(Trs1 INSEAM LEFT or Trs1 INSEAM Right)
Fabric Width                      'Fabric_Width'             for trouser ?
Plaid                             'Plaid'
Stripe                            'Stripe'                   when to pick TRS1,TRS2 ?
Offset                            'Offset' 
Fabric Way                        'Fabric_Way'     
1 Way Stripe                      '1_Way_Stripe'       
S95-SHELL SOLID                   'S95-SHELL_SOLID'          
S95-SHELL STP                     'S95-SHELL_STP'          
S95-SHELL PLAID                   'S95-SHELL_PLAID'           
BUFFER SOLID-S95                  'BUFFER_SOLID-S95'            
BUFFER STP-S95                    'BUFFER_STP-S95'          
BUFFER PLAID-S95                  'BUFFER_PLAID-S95'            
Jkt HANDMD                        'Jkt_HANDMD'       
Jkt LINING                        'Jkt_LINING'       
Jkt CHE                           'Jkt_CHE'    
Jkt GIR                           'Jkt_GIR'    
Jkt SEAT                          'Jkt_SEAT'     
Jkt LEN                           'Jkt_LEN'    
Jkt FRTLEN                        'Jkt_FRTLEN'       
Jkt PP                            'Jkt_PP'   
Jkt BCKWDTH                       'Jkt_BCKWDTH'        
Jkt SLVOUT RIGHT                  'Jkt_SLVOUT_RIGHT'             
Jkt SLVOUT LEFT                   'Jkt_SLVOUT_LEFT'            
Jkt BICEP                         'Jkt_BICEP'      
Jkt LAPK                          'Jkt_LAPK'     
Jkt LAPP                          'Jkt_LAPP'     
Jkt BTN                           'Jkt_BTN'    
Jkt WRIST                         'Jkt_WRIST'      
Jkt AHDEPTH                       'Jkt_AHDEPTH'        
Jkt VENT                          'Jkt_VENT'     
Jkt PLUSAH3                       'Jkt_PLUSAH3'        
Jkt ERECT                         'Jkt_ERECT'      
Jkt FULLCHES                      'Jkt_FULLCHES'         
Jkt HEADF                         'Jkt_HEADF'      
Jkt LOWCLR                        'Jkt_LOWCLR'        
Jkt PLUSAH2                       'Jkt_PLUSAH2'         
Jkt MINUSCLR                      'Jkt_MINUSCLR'          
Jkt SLOPE                         'Jkt_SLOPE'       
Jkt BTN1                          'Jkt_BTN1'      
Jkt BTN3                          'Jkt_BTN3'      
Jkt ROPESLV                       'Jkt_ROPESLV'         
Jkt SLANTPKT                      'Jkt_SLANTPKT'          
Jkt TKTPKT                        'Jkt_TKTPKT'        
Jkt ADDLIFT                       'Jkt_ADDLIFT'         
Jkt NOOBW                         'Jkt_NOOBW'       
Jkt NODART                        'Jkt_NODART'        
Jkt FRTEDGE                       'Jkt_FRTEDGE'         
Jkt LEARCLR                       'Jkt_LEARCLR'         
Jkt LEFTDN                        'Jkt_LEFTDN'        
Jkt RIGTDN                        'Jkt_RIGTDN'        
Jkt FULCANV                       'Jkt_FULCANV'         
Jkt HALFCANV                      'Jkt_HALFCANV'          
Jkt FLTCANV                       'Jkt_FLTCANV'         
Jkt PATCHPKT                      'Jkt_PATCHPKT'          
Jkt SLVVENT                       'Jkt_SLVVENT'         
Jkt SLVBACK                       'Jkt_SLVBACK'         
Jkt SLVFW                         'Jkt_SLVFW'       
Jkt LONDONF                       'Jkt_LONDONF'         
Jkt PORTLYF                       'Jkt_PORTLYF'         
Jkt DB                            'Jkt_DB'    
Jkt CBPLULS                       'Jkt_CBPLULS'         
Jkt SHGIRTHF                      'Jkt_SHGIRTHF'          
Jkt SHGIRTBK                     'Jkt_SHGIRTBK'          
Jkt PLTPPK                        'Jkt_PLTPPK'        
Jkt OPENDART                      'Jkt_OPENDART'          
Jkt PORTLYGRI                     'Jkt_PORTLYGRI'           
Jkt ATHLETIC                      'Jkt_ATHLETIC'          
Jkt STBTM                         'Jkt_STBTM'       
Jkt FLAPPK                        'Jkt_FLAPPK'        
Jkt BESOMP                        'Jkt_BESOMP'        
Jkt 2PATCH                        'Jkt_2PATCH'        
Jkt 2PATFL                        'Jkt_2PATFL'        
Jkt 3PATCH                        'Jkt_3PATCH'        
Jkt 3PATFL                        'Jkt_3PATFL'        
Jkt L-WELT                        'Jkt_L-WELT'        
Jkt STDPLG                        'Jkt_STDPLG'        
Jkt STDPSH                        'Jkt_STDPSH'        
Jkt CIGLG                         'Jkt_CIGLG'        
Jkt CIGSH                         'Jkt_CIGSH'        
Jkt PENPLG                        'Jkt_PENPLG'        
Jkt PENPSH                        'Jkt_PENPSH'        
Jkt CELLLG                        'Jkt_CELLLG'        
Jkt CELLSH                        'Jkt_CELLSH'        
Jkt PASSPK                        'Jkt_PASSPK'        
Jkt SVSTRA                        'Jkt_SVSTRA'        
Jkt SWEATP                        'Jkt_SWEATP'        
Jkt TKT-PK                        'Jkt_TKT-PK'        
Jkt ELBOWP                        'Jkt_ELBOWP'        
Jkt C-SETN                        'Jkt_C-SETN'        
Jkt C-SETF                        'Jkt_C-SETF'        
Jkt C-SETH                        'Jkt_C-SETH'        
Jkt RIOFAC                        'Jkt_RIOFAC'        
Jkt SOVFAC                        'Jkt_SOVFAC'        
Jkt FF                            'Jkt_FF'    
Jkt CPSLV                         'Jkt_CPSLV'        
Jkt F-YOKE                        'Jkt_YOKE'        
Jkt BELTBK                        'Jkt_BELTBK'        
Jkt US-SV-RG-HG-TR-FLG            'Jkt_US-SV-RG-HG-TR-FLG'      
Jkt US-SV-RG-HG-TR-HLG            'Jkt_US-SV-RG-HG-TR-HLG'      
Jkt US-SV-RG-HG-TR-HLG-A          'Jkt_US-SV-RG-HG-TR-HLG-A'        
Jkt US-SV-SHAWL-FLG               'Jkt_US-SV-SHAWL-FLG'   
Jkt US-SV-SHAWL-HLG               'Jkt_US-SV-SHAWL-HLG'   
Jkt US-SV-SHAWL-HLG-A             'Jkt_US-SV-SHAWL-HLG-A'     
Jkt US-SV-SRP-DRP-DB-FLG          'Jkt_US-SV-SRP-DRP-DB-FLG'        
Jkt US-SV-SRP-DRP-DB-HLG          'Jkt_US-SV-SRP-DRP-DB-HLG'        
Jkt US-SV-SRP-DRP-DB-HLG-A        'Jkt_US-SV-SRP-DRP-DB-HLG-A'          
Jkt US-CV-RG-HG-TR-FLG            'Jkt_US-CV-RG-HG-TR-FLG'      
Jkt US-CV-RG-HG-TR-HLG            'Jkt_US-CV-RG-HG-TR-HLG'      
Jkt US-CV-RG-HG-TR-HLG-A          'Jkt_US-CV-RG-HG-TR-HLG-A'        
Jkt US-CV-SHAWL-FLG               'Jkt_US-CV-SHAWL-FLG'   
Jkt US-CV-SHAWL-HLG               'Jkt_US-CV-SHAWL-HLG'   
Jkt US-CV-SHAWL-HLG-A             'Jkt_US-CV-SHAWL-HLG-A'     
Jkt US-CV-SRP-DRP-DB-FLG          'Jkt_US-CV-SRP-DRP-DB-FLG'        
Jkt US-CV-SRP-DRP-DB-HLG          'Jkt_US-CV-SRP-DRP-DB-HLG'        
Jkt US-CV-SRP-DRP-DB-HLG-A        'Jkt_US-CV-SRP-DRP-DB-HLG-A'          
Jkt US-NV-RG-HG-TR-FLG            'Jkt_US-NV-RG-HG-TR-FLG'      
Jkt US-NV-RG-HG-TR-HLG            'Jkt_US-NV-RG-HG-TR-HLG'      
Jkt US-NV-RG-HG-TR-HLG-A          'Jkt_US-NV-RG-HG-TR-HLG-A'        
Jkt US-NV-SHAWL-FLG               'Jkt_US-NV-SHAWL-FLG'   
Jkt US-NV-SHAWL-HLG               'Jkt_US-NV-SHAWL-HLG'   
Jkt US-NV-SHAWL-HLG-A             'Jkt_US-NV-SHAWL-HLG-A'     
Jkt US-NV-SRP-DRP-DB-FLG          'Jkt_US-NV-SRP-DRP-DB-FLG'        
Jkt US-NV-SRP-DRP-DB-HLG          'Jkt_US-NV-SRP-DRP-DB-HLG'        
Jkt US-NV-SRP-DRP-DB-HLG-A        'Jkt_US-NV-SRP-DRP-DB-HLG-A'          
Trs HANDMD                        'Trs_HANDMD'           
Trs LINING                        'Trs_LINING'     
Trs1 WAIST                        'Trs1_WAIST'    
Trs1 SEAT                         'Trs1_SEAT'   
Trs1 THIGH                        'Trs1_THIGH'    
Trs1 KNEE                         'Trs1_KNEE'   
Trs1 BTM                          'Trs1_BTM'  
Trs1 INSEAM RIGHT                 'Trs1_INSEAM_RIGHT'           
Trs1 INSEAM LEFT                  'Trs1_INSEAM_LEFT'          
Trs1 OTSEAM                       'Trs1_OTSEAM'     
Trs1 TRURISE                      'Trs1_TRURISE'      
Trs1 FRTRISE                      'Trs1_FRTRISE'      
Trs1 BKRISE                       'Trs1_BKRISE'     
Trs1 URISE                        'Trs1_URISE'    
Trs1 DPSEAT                       'Trs1_DPSEAT'     
Trs1 HIPFWD                       'Trs1_HIPFWD'     
Trs1 LWFRT                        'Trs1_LWFRT'    
Trs1 PLCROT                       'Trs1_PLCROT'     
Trs1 RISEBK                       'Trs1_RISEBK'     
Trs1 DEP1PLE                      'Trs1_DEP1PLE'      
Trs1 DEP2PLE                      'Trs1_DEP2PLE'      
Trs1 BPKTD                        'Trs1_BPKTD'    
Trs1 CUFF                         'Trs1_CUFF'   
Trs1 SLTHM                        'Trs1_SLTHM'    
Trs1 SQEXT                        'Trs1_SQEXT'    
Trs1 TRNPLT                       'Trs1_TRNPLT'     
Trs1 WBHT                         'Trs1_WBHT'   
Trs1 MINUSPEG                     'Trs1_MINUSPEG'       
Trs1 FRTPKTD                      'Trs1_FRTPKTD'      
Trs1 ZIPPER                       'Trs1_ZIPPER'     
Trs1 EXTENT                       'Trs1_EXTENT'     
Trs1 C-PKT                        'Trs1_C-PKT'    
Trs1 CFHKLG                       'Trs1_CFHKLG'     
Trs1 C-HKLG                       'Trs1_C-HKLG'     
Trs1 CPFKLG                       'Trs1_CPFKLG'     
Trs1 S-PKT                        'Trs1_S-PKT'    
Trs1 SFHKLG                       'Trs1_SFHKLG'     
Trs1 S-HKLG                       'Trs1_S-HKLG'     
Trs1 SPFKLG                       'Trs1_SPFKLG'     
Trs1 FB-PKT                       'Trs1_FB-PKT'     
Trs1 FFHKLG                       'Trs1_FFHKLG'     
Trs1 F-HKLG                       'Trs1_F-HKLG'     
Trs1 FPFKLG                       'Trs1_FPFKLG'     
Trs1 P-EXTN                       'Trs1_P-EXTN'     
Trs1 NOLOOP                       'Trs1_NOLOOP'     
Trs1 TNLLOP                       'Trs1_TNLLOP'     
Trs1 BKFLAP                       'Trs1_BKFLAP'     
Trs1 WATCHP                       'Trs1_WATCHP'     
Trs1 WAFLAP                       'Trs1_WAFLAP'     
Trs1 ADJTAB                       'Trs1_ADJTAB'     
Trs1 EXITAB                       'Trs1_EXITAB'     
Trs1 TABFLY                       'Trs1_TABFLY'     
Trs1 COINPK                       'Trs1_COINPK'     
Trs1 RENFLG                       'Trs1_RENFLG'     
Trs1 RENFSH                       'Trs1_RENFSH'     
Trs1 D-RING                       'Trs1_D-RING'     
Trs1 PSQUFL                       'Trs1_PSQUFL'     
Trs1 ADBUCK                       'Trs1_ADBUCK'     
Trs1 WBSKIR                       'Trs1_WBSKIR'     
Trs1 STAYBA                       'Trs1_STAYBA'     
Trs1 W-PKT                        'Trs1_W-PKT'    
Trs1 WFHKLG                       'Trs1_WFHKLG'     
Trs1 W-HKLG                       'Trs1_W-HKLG'     
Trs1 WPFKLG                       'Trs1_WPFKLG'     
Trs1 US-1PLEAT-TRS-1DART          'Trs1_US-1PLEAT-TRS-1DART'          
Trs1 US-1PLEAT-TRS-2DART          'Trs1_US-1PLEAT-TRS-2DART'          
Trs1 US-2PLEAT-TRS-1DART          'Trs1_US-2PLEAT-TRS-1DART'          
Trs1 US-2PLEAT-TRS-2DART          'Trs1_US-2PLEAT-TRS-2DART'          
Trs1 US-3PLEAT-TRS-1DART          'Trs1_US-3PLEAT-TRS-1DART'          
Trs1 US-3PLEAT-TRS-2DART          'Trs1_US-3PLEAT-TRS-2DART'          
Trs1 US-4PLEAT-TRS-1DART          'Trs1_US-4PLEAT-TRS-1DART'          
Trs1 US-4PLEAT-TRS-2DART          'Trs1_US-4PLEAT-TRS-2DART'          
Trs1 US-11-FF-TRS-1DART           'Trs1_US-11-FF-TRS-1DART'         
Trs1 US-11-FF-TRS-2DART           'Trs1_US-11-FF-TRS-2DART'         
Trs1 HARI-1PLEAT-TRS              'Trs1_HARI-1PLEAT-TRS'      
Trs1 HARI-2PLEAT-TRS              'Trs1_HARI-2PLEAT-TRS'      
Trs1 HARI-3PLEAT-TRS              'Trs1_HARI-3PLEAT-TRS'      
Trs1 HARI-4PLEAT-TRS              'Trs1_HARI-4PLEAT-TRS'        
Trs1 HARI-11-FF-TRS               'Trs1_HARI-11-FF-TRS'       
Trs2 HANDMD                       'Trs2_HANDMD'
Trs2 WAIST                        'Trs2_WAIST'
Trs2 SEAT                         'Trs2_SEAT'
Trs2 THIGH                        'Trs2_THIGH'
Trs2 KNEE                         'Trs2_KNEE'
Trs2 BTM                          'Trs2_BTM'
Trs2 INSEAM RIGHT                 'Trs2_INSEAM_RIGHT'               
Trs2 INSEAM LEFT                  'Trs2_INSEAM_LEFT'              
Trs2 OTSEAM                       'Trs2_OTSEAM'         
Trs2 TRURISE                      'Trs2_TRURISE'          
Trs2 FRTRISE                      'Trs2_FRTRISE'      
Trs2 BKRISE                       'Trs2_BKRISE'     
Trs2 URISE                        'Trs2_URISE'    
Trs2 DPSEAT                       'Trs2_DPSEAT'     
Trs2 HIPFWD                       'Trs2_HIPFWD'     
Trs2 LWFRT                        'Trs2_LWFRT'    
Trs2 PLCROT                       'Trs2_PLCROT'     
Trs2 RISEBK                       'Trs2_RISEBK'     
Trs2 DEP1PLE                      'Trs2_DEP1PLE'      
Trs2 DEP2PLE                      'Trs2_DEP2PLE'      
Trs2 BPKTD                        'Trs2_BPKTD'           
Trs2 CUFF                         'Trs2_CUFF'          
Trs2 SLTHM                        'Trs2_SLTHM'           
Trs2 SQEXT                        'Trs2_SQEXT'           
Trs2 TRNPLT                       'Trs2_TRNPLT'            
Trs2 WBHT                         'Trs2_WBHT'          
Trs2 MINUSPEG                     'Trs2_MINUSPEG'              
Trs2 FRTPKTD                      'Trs2_FRTPKTD'             
Trs2 ZIPPER                       'Trs2_ZIPPER'            
Trs2 EXTENT                       'Trs2_EXTENT'            
Trs2 C-PKT                        'Trs2_C-PKT'           
Trs2 CFHKLG                       'Trs2_CFHKLG'            
Trs2 C-HKLG                       'Trs2_C-HKLG'            
Trs2 CPFKLG                       'Trs2_CPFKLG'            
Trs2 S-PKT                        'Trs2_S-PKT'           
Trs2 SFHKLG                       'Trs2_SFHKLG'            
Trs2 S-HKLG                       'Trs2_S-HKLG'            
Trs2 SPFKLG                       'Trs2_SPFKLG'            
Trs2 FB-PKT                       'Trs2_FB-PKT'            
Trs2 FFHKLG                       'Trs2_FFHKLG'            
Trs2 F-HKLG                       'Trs2_F-HKLG'            
Trs2 FPFKLG                       'Trs2_FPFKLG'            
Trs2 P-EXTN                       'Trs2_P-EXTN'            
Trs2 NOLOOP                       'Trs2_NOLOOP'            
Trs2 TNLLOP                       'Trs2_TNLLOP'            
Trs2 BKFLAP                       'Trs2_BKFLAP'            
Trs2 WATCHP                       'Trs2_WATCHP'            
Trs2 WAFLAP                       'Trs2_WAFLAP'            
Trs2 ADJTAB                       'Trs2_ADJTAB'            
Trs2 EXITAB                       'Trs2_EXITAB'            
Trs2 TABFLY                       'Trs2_TABFLY'            
Trs2 COINPK                       'Trs2_COINPK'            
Trs2 RENFLG                       'Trs2_RENFLG'            
Trs2 RENFSH                       'Trs2_RENFSH'            
Trs2 D-RING                       'Trs2_D-RING'            
Trs2 PSQUFL                       'Trs2_PSQUFL'            
Trs2 ADBUCK                       'Trs2_ADBUCK'            
Trs2 WBSKIR                       'Trs2_WBSKIR'            
Trs2 STAYBA                       'Trs2_STAYBA'            
Trs2 W-PKT                        'Trs2_W-PKT'           
Trs2 WFHKLG                       'Trs2_WFHKLG'            
Trs2 W-HKLG                       'Trs2_W-HKLG'            
Trs2 WPFKLG                       'Trs2_WPFKLG'            
Trs2 US-1PLEAT-TRS-1DART          'Trs2_US-1PLEAT-TRS-1DART'            
Trs2 US-1PLEAT-TRS-2DART          'Trs2_US-1PLEAT-TRS-2DART'            
Trs2 US-2PLEAT-TRS-1DART          'Trs2_US-2PLEAT-TRS-1DART'            
Trs2 US-2PLEAT-TRS-2DART          'Trs2_US-2PLEAT-TRS-2DART'            
Trs2 US-3PLEAT-TRS-1DART          'Trs2_US-3PLEAT-TRS-1DART'            
Trs2 US-3PLEAT-TRS-2DART          'Trs2_US-3PLEAT-TRS-2DART'            
Trs2 US-4PLEAT-TRS-1DART          'Trs2_US-4PLEAT-TRS-1DART'            
Trs2 US-4PLEAT-TRS-2DART          'Trs2_US-4PLEAT-TRS-2DART'            
Trs2 US-11-FF-TRS-1DART           'Trs2_US-11-FF-TRS-1DART'           
Trs2 US-11-FF-TRS-2DART           'Trs2_US-11-FF-TRS-2DART'           
Trs2 HARI-1PLEAT-TRS              'Trs2_HARI-1PLEAT-TRS'        
Trs2 HARI-2PLEAT-TRS              'Trs2_HARI-2PLEAT-TRS'        
Trs2 HARI-3PLEAT-TRS              'Trs2_HARI-3PLEAT-TRS'        
Trs2 HARI-4PLEAT-TRS              'Trs2_HARI-4PLEAT-TRS'        
Trs2 HARI-11-FF-TRS               'Trs2_HARI-11-FF-TRS'       
Vst HANDMD                        'Vst_HANDMD'           
Vst LINING                        'Vst_LINING'           
Vst GIRTH                         'Vst_GIRTH'          
Vst CHE                           'Vst_CHE'        
Vst FLCB                          'Vst_FLCB'         
Vst BKL                           'Vst_BKL'        
Vst PP                            'Vst_PP'       
Vst BACKWDTH                      'Vst_BACKWDTH'             
Vst 2WELTP                        'Vst_2WELTP'           
Vst 4WELTP                        'Vst_4WELTP'           
Vst 2PIPEP                        'Vst_2PIPEP'           
Vst 4PIPEP                        'Vst_4PIPEP'           
Vst SHBACK                        'Vst_SHBACK'           
Vst Break Point-474/VS2/VS4/VS6   'Vst_Break_Po-474/VS2/VS4/VS6'           
Vst Break Point - VS-5            'Vst_Break_Po-VS-5'  
Vst Break Point - VS-I4           'Vst_Break_Po-VS-I4'   
Vst Break Point - VL9-VL22        'Vst_Break_Po-VL9-VL22'      
Vst Break Point - VL-1 / VL-10    'Vst_Break_Po-VL-1/VL-10'          
Vst Break Point - VL-8            'Vst_Break_Po-VL-8'  
Vst Break Point - VL-25           'Vst_Break_Po-VL-25'   
Vst S95-SHELL PLAID               'Vst_S95-SHELL_PLAID'         
Vst S95-SHELL SOLID               'Vst_S95-SHELL_SOLID'          
Vst S95-SHELL STP                 'Vst_S95-SHELL_STP'        
Vst BUFFER PLAID -S95             'Vst_BUFFER_PLAID-S95'           
Vst BUFFER SOLID -S95             'Vst_BUFFER_SOLID-S95'           
Vst BUFFER STP -S95               'Vst_BUFFER_STP-S95'         
Vst US-474-2WELTS-VEST            'Vst_US-474-2WELTS-VEST'            
Vst US-474-4WELTS-VEST            'Vst_US-474-4WELTS-VEST'            
Vst US-VL-1-VEST                  'Vst_US-VL-1-VEST'      
Vst US-VL-10-VEST                 'Vst_US-VL-10-VEST'       
Vst US-VL1-PEAK-VEST              'Vst_US-VL1-PEAK-VEST'          
Vst US-VL8-VEST                   'Vst_US-VL8-VEST'     
Vst US-VL9-VEST                   'Vst_US-VL9-VEST'     
Vst US-VL22-VEST                  'Vst_US-VL22-VEST'      
Vst US-VL25-VEST                  'Vst_US-VL25-VEST'      
Vst US-VS-2-VEST                  'Vst_US-VS-2-VEST'      
Vst US-VS-4-VEST                  'Vst_US-VS-4-VEST'      
Vst US-VS-5-VEST                  'Vst_US-VS-5-VEST'      
Vst US-VS-6-VEST                  'Vst_US-VS-6-VEST'      
Vst US-VS-14-VEST                 'Vst_US-VS-14-VEST'       
Trs1 RNDEXT                       
Trs1 RAISE FRONT                  'Trs1_RAISE_FRONT'      
Trs1 LOWER BACK                   'Trs1_LOWER_BACK'     
Trs2 RAISE FRONT                  'Trs2_RAISE_FRONT'      
Trs2 LOWER BACK                   'Trs2_LOWER_BACK'    
Trs1 TG-US-FF-TRS-1DART           'Trs1_TG-US-FF-TRS-1DART'              
Trs2 TG-US-FF-TRS-1DART           'Trs1_TG-US-FF-TRS-2DART'             
Dealer Name                       'Dealer_Name'
Jkt 54WIDER-FR                    'Jkt_54WIDER-FR'                     
Jkt PKT-SQ                        'Jkt_PKT-SQ'                 
Jkt SLV-CUF                       'Jkt_SLV-CUF'                  
Jkt GUNPAT                        'Jkt_GUNPAT'                 
Jkt STOTAB                        'Jkt_STOTAB'                 
Jkt SH-TAB                        'Jkt_SH-TAB'                 
Jkt NOOBW                         'Jkt_NOOBW_'      
Jkt MILL-F                        'Jkt_MILL-F'       
Jkt 1WELT                         'Jkt_1WELT'      
Jkt 1PLYBK                        'Jkt_1PLYBK'       
Jkt 2PLYBK                        'Jkt_2PLYBK'       
Trs1 33TNLLOOP                    'Trs1_33TNLLOOP'           
Trs1 34FPKTOPEN                   'Trs1_34FRTPKTOPEN'            
Trs1 35FRTDART                    'Trs1_35FRTDART'           
Trs1 NOHIPP                       'Trs1_NOHIPP'        
Trs1 BHKLG                        'Trs1_BHKLG'       
Trs1 TG-US-FF-TRS-2DART            'Trs1_TG-US-FF-TRS-2DART'  
Trs2 TG-US-FF-TRS-2DART            'Trs2_TG-US-FF-TRS-2DART'  
Jkt FLATCHEST                      'Jkt_FLATCHEST'             
Jkt HN                             'Jkt_HN'     
Jkt OPENBK                         'Jkt_OPENBK'            
Trs1 DEPTURN1                      'Trs1_DEPTURN1'             
Trs1 DEPTURN2                      'Trs1_DEPTURN2'             
Trs1 18PKT                         'Trs1_18PKT'          
Trs1 JNW                           'Trs1_JNW'        
Trs1 JNN                           'Trs2_JNN'        
Vst AVSTGR                         'Vst_AVSTGR'
Jkt NOVSLV                         'Jkt_NOVSLV'
Jkt BISWBK                         'Jkt_BISWBK'
Jkt STBKYK                         'Jkt_STBKYK'
Jkt STFRYK                         'Jkt_STFRYK' 



///Trs1 RNDEXT